# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ebertech-snapshot}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Eberbach"]
  s.date = %q{2011-05-25}
  s.default_executable = %q{snapshot}
  s.email = %q{andrew@ebertech.ca}
  s.executables = ["snapshot"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "VERSION",
    "lib/ebertech-snapshot.rb",
    "lib/ebertech/snapshot/command.rb",
    "lib/ebertech/snapshot/commands/init_command.rb",
    "lib/ebertech/snapshot/commands/list_revisions_command.rb",
    "lib/ebertech/snapshot/commands/list_tags_command.rb",
    "lib/ebertech/snapshot/commands/mark_clean_command.rb",
    "lib/ebertech/snapshot/commands/mark_dirty_command.rb",
    "lib/ebertech/snapshot/commands/migrate_command.rb",
    "lib/ebertech/snapshot/commands/pull_command.rb",
    "lib/ebertech/snapshot/commands/push_command.rb",
    "lib/ebertech/snapshot/commands/remove_tag_command.rb",
    "lib/ebertech/snapshot/commands/reset_command.rb",
    "lib/ebertech/snapshot/commands/save_command.rb",
    "lib/ebertech/snapshot/commands/start_database_command.rb",
    "lib/ebertech/snapshot/commands/stop_database_command.rb",
    "lib/ebertech/snapshot/configuration.rb",
    "lib/ebertech/snapshot/generator/snapshot_generator.rb",
    "lib/ebertech/snapshot/generator/templates/database.yml",
    "lib/ebertech/snapshot/generator/templates/snapshot.rb",
    "lib/ebertech/snapshot/generator/templates/snapshot.yml"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Save the database into a git-managed snapshot}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.5"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.5"])
      s.add_dependency(%q<highline>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.5"])
    s.add_dependency(%q<highline>, [">= 0"])
  end
end

