# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{snapshot.ebertech.ca}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Eberbach"]
  s.date = %q{2010-10-04}
  s.default_executable = %q{snapshot}
  s.email = %q{andrew@ebertech.ca}
  s.executables = ["snapshot"]
  s.files = [
    "VERSION",
     "lib/ebertech/snapshot/command.rb",
     "lib/ebertech/snapshot/commands/create_config_command.rb",
     "lib/ebertech/snapshot/commands/init_command.rb",
     "lib/ebertech/snapshot/commands/list_revisions_command.rb",
     "lib/ebertech/snapshot/commands/list_tags_command.rb",
     "lib/ebertech/snapshot/commands/mark_clean_command.rb",
     "lib/ebertech/snapshot/commands/mark_dirty_command.rb",
     "lib/ebertech/snapshot/commands/remove_tag_command.rb",
     "lib/ebertech/snapshot/commands/reset_command.rb",
     "lib/ebertech/snapshot/commands/save_snapshot_command.rb",
     "lib/ebertech/snapshot/commands/start_database_command.rb",
     "lib/ebertech/snapshot/commands/stop_database_command.rb",
     "lib/ebertech/snapshot/configuration.rb",
     "lib/snapshot.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Save the database into a git-managed snapshot}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

