--- 
<%= environment_name %>: &TEST
  username: <%= username %>
  adapter: mysql
  database: <%= database %>
  socket: <%= socket %>
  encoding: utf8
  <%- if port -%>
  port: <%= port %>
  <%- end -%>
  
cucumber: &CUCUMBER
  <<: *TEST
culerity:
  <<: *TEST
test:
  <<: *TEST
